version: "3.7"

services:
  fastapi-app:
    build: .
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DOMAIN=${DOMAIN}
      - API_VERSION=${API_VERSION}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SERVICE_PORT=${SERVICE_PORT}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: domain_lookup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
