version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: shathishwarmas
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: shathishwarmas
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shathishwarmas"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://shathishwarmas:newpassword@postgres/shathishwarmas
    depends_on:
      postgres:
        condition: service_healthy
