name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11'] # Testing on multiple Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pytest --cov=app tests/

  docker_build:
    runs-on: ubuntu-latest
    needs: build # This job depends on the success of the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t shathish/fastapi:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push shathish/fastapi:${{ github.sha }}

  package_helm:
    runs-on: ubuntu-latest
    needs: docker_build # This job depends on the success of the docker_build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package Helm chart
        run: |
          helm package helm/fastapi-app

      - name: Helm Lint
        run: |
          helm lint helm/fastapi-app
