name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pytest --cov=app tests/

      - name: Build Docker image
        run: |
          docker build -t your-docker-repo/fastapi-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-docker-repo/fastapi-app:${{ github.sha }}

      - name: Package Helm chart
        run: |
          helm package helm/fastapi-app

      - name: Helm Lint
        run: |
          helm lint helm/fastapi-app
